language: android
os: linux
dist: xenial
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-29
install:
  - yes | sdkmanager "platform-tools" "platforms;android-29" "build-tools;28.0.3"
  - git clone https://github.com/flutter/flutter.git -b flutter-1.22-candidate.9
script:
  - ./flutter/bin/flutter build apk --debug
deploy:
  provider: releases
  api_key: $API_KEY
  file: build/app/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true